# Generated by Django 5.0 on 2025-05-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='company_logos/'),
        ),
    ]
