# Generated by Django 5.2.1 on 2025-06-02 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_options_company_is_active_subscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', help_text='Billing cadence for this plan.', max_length=20)),
                ('features', models.TextField(help_text='List features of this plan, one per line.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to retire a plan so that new orders cannot choose it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active_subscription',
            field=models.BooleanField(default=False, help_text='If False (or expired), this tenant’s site is inactive.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo (optional)', null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='on_trial',
            field=models.BooleanField(default=True, help_text='Whether this company is still on trial.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='paid_until',
            field=models.DateField(blank=True, help_text='Date when the subscription expires.', null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Order status: pending → approved → rejected.', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total cost of this order (e.g. plan.price).', max_digits=10)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], help_text='Billing cadence for this order (copied from Plan).', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes or special requirements.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='companies.company')),
                ('plan', models.ForeignKey(help_text='Which plan the company wants to purchase.', on_delete=django.db.models.deletion.CASCADE, to='companies.plan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='current_plan',
            field=models.ForeignKey(blank=True, help_text='The subscription plan this company is currently using.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.plan'),
        ),
    ]
